title: "Ardy's Blog"
description: ""
url: "https://0xardy.github.io"
baseurl: ""
og_image: "/assets/images/og-panda-bamboo-x-card.png"
twitter_username: "0xardy"
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
timezone: "UTC"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      og_image: "/assets/images/og-panda-bamboo-x-card.png"
